#!/usr/bin/env python3
"""
WASM Export Section Adder
Add export section to WASM binary generated by llvmlite
"""

import sys

def write_varuint(value):
    """Encode unsigned integer as LEB128"""
    result = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value != 0:
            result.append(byte | 0x80)
        else:
            result.append(byte)
            break
    return bytes(result)

def write_name(name):
    """Encode name (length + UTF-8 bytes)"""
    name_bytes = name.encode('utf-8')
    return write_varuint(len(name_bytes)) + name_bytes

def add_export_section(wasm_data, exports):
    """
    Add export section to WASM binary

    Args:
        wasm_data: Original WASM binary
        exports: List of (name, kind, index) tuples
                 kind: 0=func, 1=table, 2=mem, 3=global

    Returns:
        Modified WASM binary with export section
    """
    # Check magic and version
    if wasm_data[0:4] != b'\x00asm':
        raise ValueError("Invalid WASM magic")

    # Build export section
    export_entries = bytearray()
    export_entries.extend(write_varuint(len(exports)))  # count

    for name, kind, index in exports:
        export_entries.extend(write_name(name))
        export_entries.append(kind)
        export_entries.extend(write_varuint(index))

    export_section = bytearray()
    export_section.append(7)  # section id: Export
    export_section.extend(write_varuint(len(export_entries)))
    export_section.extend(export_entries)

    # Find insertion point (before Code section or at end)
    # WASM section order: Type(1) Import(2) Function(3) ... Export(7) ... Code(10)
    offset = 8  # Skip magic + version
    sections = []

    while offset < len(wasm_data):
        section_id = wasm_data[offset]
        offset += 1

        # Read section size (varuint)
        size = 0
        shift = 0
        size_start = offset
        while True:
            byte = wasm_data[offset]
            offset += 1
            size |= (byte & 0x7F) << shift
            if (byte & 0x80) == 0:
                break
            shift += 7

        section_header = wasm_data[size_start-1:offset]
        section_body = wasm_data[offset:offset+size]
        sections.append((section_id, section_header, section_body))
        offset += size

    # Rebuild WASM with export section inserted
    result = bytearray(wasm_data[0:8])  # magic + version

    # Insert export section before Code(10) or at end
    export_inserted = False
    for section_id, header, body in sections:
        if not export_inserted and section_id >= 8:
            # Insert export section before this section
            result.extend(export_section)
            export_inserted = True

        result.extend(header)
        result.extend(body)

    if not export_inserted:
        # Add at end
        result.extend(export_section)

    return bytes(result)

def main():
    if len(sys.argv) < 3:
        print("Usage: wasm_add_export.py <input.wasm> <output.wasm> [exports]")
        print()
        print("Examples:")
        print("  # Export ny_main function (index 0)")
        print("  wasm_add_export.py in.wasm out.wasm ny_main:func:0")
        print()
        print("  # Export multiple")
        print("  wasm_add_export.py in.wasm out.wasm ny_main:func:0 memory:mem:0")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    # Parse export specs
    exports = []
    if len(sys.argv) > 3:
        for spec in sys.argv[3:]:
            parts = spec.split(':')
            if len(parts) != 3:
                print(f"Invalid export spec: {spec}")
                print("Format: name:kind:index")
                print("  kind: func, table, mem, global")
                sys.exit(1)

            name = parts[0]
            kind_str = parts[1]
            index = int(parts[2])

            kind_map = {"func": 0, "table": 1, "mem": 2, "global": 3}
            if kind_str not in kind_map:
                print(f"Invalid kind: {kind_str}")
                sys.exit(1)

            exports.append((name, kind_map[kind_str], index))
    else:
        # Default: export ny_main function at index 0
        exports = [("ny_main", 0, 0)]

    # Read input
    with open(input_file, 'rb') as f:
        wasm_data = f.read()

    print(f"Input: {input_file} ({len(wasm_data)} bytes)")
    print(f"Exports to add:")
    for name, kind, index in exports:
        kind_name = {0: "func", 1: "table", 2: "mem", 3: "global"}[kind]
        print(f"  - {name} ({kind_name} {index})")

    # Add export section
    modified = add_export_section(wasm_data, exports)

    # Write output
    with open(output_file, 'wb') as f:
        f.write(modified)

    print(f"✅ Output: {output_file} ({len(modified)} bytes, +{len(modified)-len(wasm_data)} bytes)")

if __name__ == "__main__":
    main()
