/*!
 * Type Registry (Tier-0 雛形)
 *
 * 目的:
 * - TypeId → TypeBox 参照の最小インターフェースを用意（現時点では未実装・常に未登録）。
 * - VM/JIT 実装が存在を前提に呼び出しても no-op/fallback できる状態にする。
 *
 * スロット番号の方針（注釈）
 * - ここで定義する `slot` は「VTable 用の仮想メソッドID」です。VM/JIT の内部ディスパッチ最適化
 *   と、Builtin Box の高速経路（fast path）に使われます。
 * - HostAPI（プラグインのネイティブ関数呼び出し）で用いるメソッド番号空間とは独立です。
 *   HostAPI 側は TLV で型付き引数を渡し、プラグイン実装側の関数テーブルにマップされます。
 *   そのため重複しても問題ありません（互いに衝突しない設計）。
 * - 慣例として以下の帯域を利用します（将来の整理用の目安）：
 *   - 0..=3: ユニバーサルスロット（toString/type/equal/copy 相当）
 *   - 100..: Array 系（get/set/len ほか拡張）
 *   - 200..: Map 系（size/len/has/get/set/delete ほか拡張）
 *   - 300..: String 系（len/substring/concat/indexOf/replace/trim/toUpper/toLower）
 *   - 400..: Console 系（log/warn/error/clear）
 */

use super::type_box_abi::{MethodEntry, TypeBox};
use once_cell::sync::Lazy;
use std::collections::HashMap;

use once_cell::sync::OnceCell;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct SsotMethod { name: String, arities: Vec<usize>, slot: u16 }
#[derive(Debug, Deserialize)]
struct SsotType { #[serde(default)] type_id: Option<u32>, methods: Vec<SsotMethod> }
#[derive(Debug, Deserialize)]
struct SsotRoot { #[serde(rename = "type")] r#type: std::collections::HashMap<String, SsotType> }

#[derive(Default)]
struct SsotRegistry {
    types: std::collections::HashMap<String, (Option<u32>, std::collections::HashMap<String, (u16, Vec<usize>)>)>,
}
static SSOT_REG: OnceCell<Option<SsotRegistry>> = OnceCell::new();

fn ssot_load() -> Option<&'static SsotRegistry> {
    SSOT_REG.get_or_init(|| {
        // Allow disabling SSOT at runtime for compatibility or bisecting.
        let disabled = std::env::var("HAKO_REGISTRY_SSOT_DISABLE")
            .ok()
            .or_else(|| std::env::var("NYASH_REGISTRY_SSOT_DISABLE").ok())
            .map(|v| v.to_ascii_lowercase())
            .map(|v| matches!(v.as_str(), "1" | "true" | "on"))
            .unwrap_or(false);
        if disabled { return None; }
        let raw = REGISTRY_SSOT_RAW?;
        let parsed: SsotRoot = match toml::from_str(raw) { Ok(v)=>v, Err(_)=> return Some(SsotRegistry::default()) };
        let mut reg = SsotRegistry::default();
        for (name, ty) in parsed.r#type.into_iter() {
            let mut methods = std::collections::HashMap::new();
            for m in ty.methods.into_iter() {
                methods.entry(m.name).and_modify(|e: &mut (u16, Vec<usize>)| {
                    // merge arities
                    let (slot_existing, arrs_existing) = e;
                    if *slot_existing == 0 { *slot_existing = m.slot; }
                    for a in m.arities.iter() {
                        if !arrs_existing.contains(a) { arrs_existing.push(*a); }
                    }
                }).or_insert_with(|| (m.slot, m.arities));
            }
            reg.types.insert(name, (ty.type_id, methods));
        }
        Some(reg)
    }).as_ref()
}

fn ssot_resolve_slot_by_name(type_name: &str, method: &str, arity: usize) -> Option<u16> {
    let reg = ssot_load()?;
    let (_tid, methods) = reg.types.get(type_name)?;
    let (slot, arities) = methods.get(method)?;
    if arities.contains(&arity) { Some(*slot) } else { None }
}

fn ssot_known_arities_for(type_name: &str, method: &str) -> Option<Vec<u8>> {
    let reg = ssot_load()?;
    let (_tid, methods) = reg.types.get(type_name)?;
    let (_slot, arities) = methods.get(method)?;
    let mut v: Vec<u8> = arities.iter().map(|x| *x as u8).collect();
    v.sort(); v.dedup();
    Some(v)
}

use crate::box_trait::NyashBox;

// Optional SSOT raw TOML presence (generated by build.rs). Not yet parsed here; future work.
include!(concat!(env!("OUT_DIR"), "/registry_ssot_generated.rs"));

// Build TypeBox tables from SSOT for diagnostics/arity checks when available.
static SSOT_TB: OnceCell<Option<std::collections::HashMap<String, TypeBox>>> = OnceCell::new();

fn ssot_typeboxes() -> Option<&'static std::collections::HashMap<String, TypeBox>> {
    SSOT_TB.get_or_init(|| {
        let ss = ssot_load()?;
        let mut map: std::collections::HashMap<String, TypeBox> = std::collections::HashMap::new();
        for (name, (_tid, methods)) in ss.types.iter() {
            let mut m: Vec<MethodEntry> = Vec::new();
            for (mn, (slot, arities)) in methods.iter() {
                for ar in arities.iter() {
                    m.push(MethodEntry { name: Box::leak(mn.clone().into_boxed_str()), arity: *ar as u8, slot: *slot });
                }
            }
            // Ensure stable order for deterministic diagnostics
            m.sort_by(|a,b| a.slot.cmp(&b.slot).then(a.name.cmp(b.name)).then(a.arity.cmp(&b.arity)));
            map.insert(name.clone(), TypeBox::new_with(Box::leak(name.clone().into_boxed_str()), Box::leak(m.into_boxed_slice())));
        }
        Some(map)
    }).as_ref()
}

// 最小サンプル: MapBox の TypeBox を事前登録（Tier-1 PoC 用）
// --- ArrayBox ---
const ARRAY_METHODS: &[MethodEntry] = &[
    MethodEntry {
        name: "get",
        arity: 1,
        slot: 100,
    },
    MethodEntry {
        name: "set",
        arity: 2,
        slot: 101,
    },
    MethodEntry {
        name: "len",
        arity: 0,
        slot: 102,
    },
    MethodEntry {
        name: "length",
        arity: 0,
        slot: 102,
    },
    MethodEntry {
        name: "size",
        arity: 0,
        slot: 102,
    },
    // P0: vtable coverage extension
    MethodEntry {
        name: "push",
        arity: 1,
        slot: 103,
    },
    MethodEntry {
        name: "pop",
        arity: 0,
        slot: 104,
    },
    MethodEntry {
        name: "clear",
        arity: 0,
        slot: 105,
    },
    // P1: contains/indexOf/join
    MethodEntry {
        name: "contains",
        arity: 1,
        slot: 106,
    },
    MethodEntry {
        name: "indexOf",
        arity: 1,
        slot: 107,
    },
    MethodEntry {
        name: "join",
        arity: 1,
        slot: 108,
    },
    // P2: sort/reverse/slice
    MethodEntry {
        name: "sort",
        arity: 0,
        slot: 109,
    },
    MethodEntry {
        name: "reverse",
        arity: 0,
        slot: 110,
    },
    MethodEntry {
        name: "slice",
        arity: 2,
        slot: 111,
    },
    MethodEntry {
        name: "toJSON",
        arity: 0,
        slot: 112,
    },

    MethodEntry { name: "methodRef", arity: 2, slot: 113 },];
static ARRAYBOX_TB: TypeBox = TypeBox::new_with("ArrayBox", ARRAY_METHODS);

// --- MapBox ---
const MAP_METHODS: &[MethodEntry] = &[
    MethodEntry {
        name: "size",
        arity: 0,
        slot: 200,
    },
    MethodEntry {
        name: "len",
        arity: 0,
        slot: 201,
    },
    MethodEntry {
        name: "has",
        arity: 1,
        slot: 202,
    },
    MethodEntry {
        name: "get",
        arity: 1,
        slot: 203,
    },
    MethodEntry {
        name: "set",
        arity: 2,
        slot: 204,
    },
    // Extended
    MethodEntry {
        name: "delete",
        arity: 1,
        slot: 205,
    }, // alias: remove (同一スロット)
    MethodEntry {
        name: "remove",
        arity: 1,
        slot: 205,
    },
    MethodEntry {
        name: "keys",
        arity: 0,
        slot: 206,
    },
    MethodEntry {
        name: "values",
        arity: 0,
        slot: 207,
    },
    MethodEntry {
        name: "clear",
        arity: 0,
        slot: 208,
    },
    MethodEntry {
        name: "toJSON",
        arity: 0,
        slot: 209,
    },

    // Callable helpers (thin sugar)
    MethodEntry { name: "call",      arity: 2, slot: 210 },
    MethodEntry { name: "callAsync", arity: 2, slot: 211 }
];
static MAPBOX_TB: TypeBox = TypeBox::new_with("MapBox", MAP_METHODS);

// --- StringBox ---
const STRING_METHODS: &[MethodEntry] = &[
    // length/size aliases
    MethodEntry { name: "len",     arity: 0, slot: 300 },
    MethodEntry { name: "length",  arity: 0, slot: 300 },
    MethodEntry { name: "size",    arity: 0, slot: 300 },

    // P1: core ops
    MethodEntry { name: "isEmpty",    arity: 0, slot: 312 },
    MethodEntry { name: "substring",  arity: 2, slot: 301 },
    MethodEntry { name: "charAt",     arity: 1, slot: 314 },
    // indexOf/lastIndexOf allow optional 'from' → duplicate arity entries share slot
    MethodEntry { name: "indexOf",     arity: 1, slot: 303 },
    MethodEntry { name: "indexOf",     arity: 2, slot: 303 },
    MethodEntry { name: "lastIndexOf", arity: 1, slot: 313 },
    MethodEntry { name: "lastIndexOf", arity: 2, slot: 313 },

    // P1: extend String vtable (kept for future)
    MethodEntry { name: "concat",   arity: 1, slot: 302 },
    MethodEntry { name: "replace",  arity: 2, slot: 304 },
    MethodEntry { name: "trim",     arity: 0, slot: 305 },
    MethodEntry { name: "toUpper",  arity: 0, slot: 306 },
    MethodEntry { name: "toLower",  arity: 0, slot: 307 },
    MethodEntry { name: "toString", arity: 0, slot: 308 },
    MethodEntry { name: "stringify",arity: 0, slot: 309 },
    MethodEntry { name: "startsWith",arity: 1, slot: 310 },
    MethodEntry { name: "endsWith",  arity: 1, slot: 311 },
];
static STRINGBOX_TB: TypeBox = TypeBox::new_with("StringBox", STRING_METHODS);

// --- ConsoleBox --- (WASM v2 unified dispatch 用の雛形)
// 400: log(..), 401: warn(..), 402: error(..), 403: clear()
const CONSOLE_METHODS: &[MethodEntry] = &[
    MethodEntry {
        name: "log",
        arity: 1,
        slot: 400,
    },
    MethodEntry {
        name: "warn",
        arity: 1,
        slot: 401,
    },
    MethodEntry {
        name: "error",
        arity: 1,
        slot: 402,
    },
    MethodEntry {
        name: "clear",
        arity: 0,
        slot: 403,
    },
];
static CONSOLEBOX_TB: TypeBox = TypeBox::new_with("ConsoleBox", CONSOLE_METHODS);

// --- CallableBox ---
const CALLABLE_METHODS: &[MethodEntry] = &[
    MethodEntry { name: "arity",     arity: 0, slot: 500 },
    MethodEntry { name: "call",      arity: 1, slot: 501 },
    MethodEntry { name: "callAsync", arity: 1, slot: 502 },
    MethodEntry { name: "toString",  arity: 0, slot: 503 },
];
static CALLABLEBOX_TB: TypeBox = TypeBox::new_with("CallableBox", CALLABLE_METHODS);


// --- InstanceBox ---
// Representative methods exposed via unified slots for field access and diagnostics.
// 1: getField(name)
// 2: setField(name, value)
// 3: has(name)
// 4: size()
const INSTANCE_METHODS: &[MethodEntry] = &[
    MethodEntry {
        name: "getField",
        arity: 1,
        slot: 1,
    },
    MethodEntry {
        name: "setField",
        arity: 2,
        slot: 2,
    },
    MethodEntry {
        name: "has",
        arity: 1,
        slot: 3,
    },
    MethodEntry {
        name: "size",
        arity: 0,
        slot: 4,
    },
];
static INSTANCEBOX_TB: TypeBox = TypeBox::new_with("InstanceBox", INSTANCE_METHODS);

/// 型名から TypeBox を解決（雛形）。現在は常に None。
pub fn resolve_typebox_by_name(type_name: &str) -> Option<&'static TypeBox> {
    if let Some(tb_map) = ssot_typeboxes() {
        if let Some(tb) = tb_map.get(type_name) { return Some(tb); }
    }
    match type_name {
        "MapBox" => Some(&MAPBOX_TB),
        "ArrayBox" => Some(&ARRAYBOX_TB),
        "StringBox" => Some(&STRINGBOX_TB),
        "ConsoleBox" => Some(&CONSOLEBOX_TB),
        "CallableBox" => Some(&CALLABLEBOX_TB),
        "InstanceBox" => Some(&INSTANCEBOX_TB),
        _ => None,
    }
}

/// 型名・メソッド名・アリティからスロットを解決（雛形）
pub fn resolve_slot_by_name(type_name: &str, method: &str, arity: usize) -> Option<u16> {
    if let Some(slot) = ssot_resolve_slot_by_name(type_name, method, arity) { return Some(slot); }
    let tb = resolve_typebox_by_name(type_name)?;
    let ar = arity as u8;
    for m in tb.methods { if m.name == method && m.arity == ar { return Some(m.slot); } }
    None
}

/// Return list of known methods for a type (names only) for diagnostics.
pub fn known_methods_for(type_name: &str) -> Option<Vec<&'static str>> {
    let tb = resolve_typebox_by_name(type_name)?;
    let mut v: Vec<&'static str> = tb.methods.iter().map(|m| m.name).collect();
    v.sort();
    v.dedup();
    Some(v)
}

/// Return list of known arities for a specific method name on a type.
pub fn known_arities_for(type_name: &str, method: &str) -> Option<Vec<u8>> {
    if let Some(v) = ssot_known_arities_for(type_name, method) { return Some(v); }
    let tb = resolve_typebox_by_name(type_name)?;
    let mut v: Vec<u8> = tb.methods.iter().filter(|m| m.name == method).map(|m| m.arity).collect();
    if v.is_empty() { return Some(vec![]); }
    v.sort(); v.dedup();
    Some(v)
}

// ---- Builtin Method Ids (Hako ABI ids for core boxes) ----


/// Resolve canonical method_id for builtin boxes (Hako ABI ids)
pub fn resolve_builtin_method_id(type_name: &str, method: &str) -> Option<u32> {
    match type_name {
        "StringBox" => match method {
            "length" | "size" | "len" => Some(1),
            "isEmpty" => Some(2),
            "charCodeAt" => Some(3),
            "concat" => Some(4),
            "fromUtf8" => Some(5),
            "toUtf8" | "toString" => Some(6),
            "substring" => Some(7),
            "indexOf" => Some(8),
            "lastIndexOf" => Some(9),
            "charAt" => Some(10),
            _ => None,
        },
        "ArrayBox" => match method {
            "length" | "size" | "len" => Some(1),
            "get" => Some(2),
            "push" => Some(3),
            _ => None,
        },
        "MapBox" => match method {
            "size" => Some(1),
            "get" => Some(2),
            _ => None,
        },
        _ => None,
    }
}

/// Unified builtin handle resolver: (type_id, method_id)
pub fn resolve_builtin_method_handle(
    type_name: &str,
    method: &str,
) -> Option<(u32, u32)> {
    let tid = builtin_type_id(type_name)?;
    let mid = resolve_builtin_method_id(type_name, method)?;
    Some((tid, mid))
}

// ---- Core type ids & helpers (SSOT) ----------------------------------------

/// Canonical Hako ABI type ids for core boxes (SSOT)
/// Core box registry (SSOT): type_name -> (type_id, factory)
#[derive(Copy, Clone)]
pub struct CoreBoxEntry {
    pub type_id: u32,
    pub factory: fn(&[Box<dyn NyashBox>]) -> Result<Box<dyn NyashBox>, crate::box_factory::RuntimeError>,
}

#[inline]
#[cfg(feature = "legacy-boxes")]
fn create_array_box(_args: &[Box<dyn NyashBox>]) -> Result<Box<dyn NyashBox>, crate::box_factory::RuntimeError> {
    Ok(Box::new(crate::boxes::array::ArrayBox::new()))
}
#[cfg(not(feature = "legacy-boxes"))]
#[inline]
fn create_array_box(args: &[Box<dyn NyashBox>]) -> Result<Box<dyn NyashBox>, crate::box_factory::RuntimeError> {
    crate::runtime::plugin_host_box::create_box("ArrayBox", args)
        .map_err(|e| crate::box_factory::RuntimeError::InvalidOperation { message: format!("plugin ArrayBox create failed: {:?}", e) })
}

#[cfg(feature = "legacy-boxes")]
#[inline]
fn create_map_box(_args: &[Box<dyn NyashBox>]) -> Result<Box<dyn NyashBox>, crate::box_factory::RuntimeError> {
    Ok(Box::new(crate::boxes::map_box::MapBox::new()))
}
#[cfg(not(feature = "legacy-boxes"))]
#[inline]
fn create_map_box(args: &[Box<dyn NyashBox>]) -> Result<Box<dyn NyashBox>, crate::box_factory::RuntimeError> {
    crate::runtime::plugin_host_box::create_box("MapBox", args)
        .map_err(|e| crate::box_factory::RuntimeError::InvalidOperation { message: format!("plugin MapBox create failed: {:?}", e) })
}
#[inline]
fn create_string_box(args: &[Box<dyn NyashBox>]) -> Result<Box<dyn NyashBox>, crate::box_factory::RuntimeError> {
    if args.is_empty() {
        Ok(Box::new(crate::box_trait::StringBox::new("")))
    } else {
        Ok(Box::new(crate::box_trait::StringBox::new(&args[0].to_string_box().value)))
    }
}

pub static CORE_BOXES: Lazy<HashMap<&'static str, CoreBoxEntry>> = Lazy::new(|| {
    let mut m = HashMap::new();
    // Resolve type ids with priority: SSOT -> config (hako/nyash.toml) -> defaults.
    let ids_from_config = (|| {
        for cfg in ["hako.toml", "nyash.toml", "hakorune.toml"].iter() {
            if let Ok(conf) = crate::config::nyash_toml_v2::NyashConfigV2::from_file(cfg) {
                if !conf.box_types.is_empty() { return conf.box_types; }
            }
        }
        HashMap::new()
    })();
    let tid = |name: &str, d: u32| -> u32 {
        // SSOT first
        if let Some(ss) = ssot_load() {
            if let Some((maybe_id, _)) = ss.types.get(name) {
                if let Some(id) = maybe_id { return *id; }
            }
        }
        // Config next
        if let Some(id) = ids_from_config.get(name) { return *id; }
        // Default fallback
        d
    };
    m.insert("MapBox",    CoreBoxEntry { type_id: tid("MapBox", 11), factory: create_map_box });
    m.insert("ArrayBox",  CoreBoxEntry { type_id: tid("ArrayBox", 12), factory: create_array_box });
    m.insert("StringBox", CoreBoxEntry { type_id: tid("StringBox", 13), factory: create_string_box });
    m
});

/// Return true when the given type name is a core box (Map/Array/String)
#[inline]
pub fn is_core_box(type_name: &str) -> bool {
    CORE_BOXES.contains_key(type_name)
}

/// Return canonical Hako ABI type_id for builtin boxes (via CORE_TYPE_IDS)
pub fn builtin_type_id(type_name: &str) -> Option<u32> {
    CORE_BOXES.get(type_name).map(|e| e.type_id)
}


/// Create a core box instance (ArrayBox/MapBox/StringBox).
/// Returns None if `type_name` is not a core box.
pub fn create_core_box(
    type_name: &str,
    args: &[Box<dyn NyashBox>],
) -> Option<Result<Box<dyn NyashBox>, crate::box_factory::RuntimeError>> {

    let entry = CORE_BOXES.get(type_name)?;
    return Some((entry.factory)(args));
    /* old match removed */
/*
        "ArrayBox" => Ok(Box::new(crate::boxes::array::ArrayBox::new()) as Box<dyn NyashBox>),
        "MapBox"   => Ok(Box::new(crate::boxes::map_box::MapBox::new()) as Box<dyn NyashBox>),
        "StringBox" => {
            if args.is_empty() {
                Ok(Box::new(crate::box_trait::StringBox::new("")) as Box<dyn NyashBox>)
            } else {
                Ok(Box::new(crate::box_trait::StringBox::new(&args[0].to_string_box().value)) as Box<dyn NyashBox>)
            }
        }
        _ => return Some(Err(RuntimeError::InvalidOperation { message: format!("Unknown core box: {}", type_name) })),
    */

}
