// @generated by build.rs from specs/externs/registry.toml
pub fn generated_externs() -> &'static [(&'static str, usize, bool)] {
    &[
        ("env.console.log", 1, true),
        ("env.console.warn", 1, true),
        ("env.console.error", 1, true),
        ("env.future.new", 1, true),
        ("env.future.set", 2, true),
        ("env.future.await", 1, true),
        ("env.local.get", 1, false),
        ("nyrt.ops.op_eq", 2, false),
        ("env.debug.trace", 1, true),
    ]
}
