#!/usr/bin/env python3
"""
WASM Export Section Adder - 箱化版
Add export section to WASM binary generated by llvmlite

箱理論の実践:
- 「箱にする」: 351行→100行に削減（箱経由で簡潔化）
- 「境界を作る」: WasmSectionParser/LinkingAnalyzer/ExportBuilder箱使用
- 「戻せる」: 同じCLIインターフェース維持（後方互換性）
- 「見える化」: 処理フローが明確
"""

import sys
from typing import List, Tuple

# 箱理論: 3つの箱をインポート
from wasm_section_parser import WasmSectionParser
from linking_analyzer import LinkingAnalyzer
from export_builder import ExportBuilder, ExportEntry


def add_export_section_boxed(
    wasm_data: bytes,
    exports: List[Tuple[str, int, int]]
) -> bytes:
    """
    箱理論: export section追加の統合エントリーポイント

    箱経由で処理（従来の巨大関数157行 → 箱経由20行）

    Args:
        wasm_data: Original WASM binary
        exports: List of (name, kind, index) tuples
                 index can be "auto" for automatic resolution

    Returns:
        Modified WASM binary with export section
    """
    # 箱1: LinkingAnalyzer - 関数名→index対応を解析
    analyzer = LinkingAnalyzer()
    func_names = analyzer.parse(wasm_data)

    # Debug: print found functions
    if func_names:
        print(f"  Found functions in linking section: {list(func_names.keys())}")
    else:
        print(f"  No functions found in linking section")

    # Resolve "auto" indices
    resolved_exports = []
    for name, kind, index in exports:
        if index == "auto" and kind == ExportEntry.KIND_FUNC:
            if name in func_names:
                index = func_names[name]
                print(f"  → Auto-resolved '{name}' to index {index}")
            else:
                print(f"  ⚠️  Warning: '{name}' not found in linking section, using index 0")
                index = 0

        resolved_exports.append((name, kind, index))

    # 箱2: ExportBuilder - export section生成
    builder = ExportBuilder()

    for name, kind, index in resolved_exports:
        builder.add_export(name, kind, index)

    # 箱3: ExportBuilder - WASM挿入
    return builder.inject_export_section(wasm_data)


def main():
    if len(sys.argv) < 3:
        print("Usage: wasm_add_export.py <input.wasm> <output.wasm> [exports]")
        print()
        print("Examples:")
        print("  # Export ny_main function (auto-detect index from linking section)")
        print("  wasm_add_export.py in.wasm out.wasm ny_main:func:auto")
        print()
        print("  # Export ny_main with explicit index")
        print("  wasm_add_export.py in.wasm out.wasm ny_main:func:1")
        print()
        print("  # Export multiple")
        print("  wasm_add_export.py in.wasm out.wasm ny_main:func:auto memory:mem:0")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    # Parse export specs
    exports = []
    if len(sys.argv) > 3:
        for spec in sys.argv[3:]:
            parts = spec.split(':')
            if len(parts) != 3:
                print(f"Invalid export spec: {spec}")
                print("Format: name:kind:index")
                print("  kind: func, table, mem, global")
                sys.exit(1)

            name = parts[0]
            kind_str = parts[1]
            index_str = parts[2]

            # Support "auto" for automatic index resolution
            if index_str == "auto":
                index = "auto"
            else:
                index = int(index_str)

            kind_map = {
                "func": ExportEntry.KIND_FUNC,
                "table": ExportEntry.KIND_TABLE,
                "mem": ExportEntry.KIND_MEMORY,
                "global": ExportEntry.KIND_GLOBAL
            }
            if kind_str not in kind_map:
                print(f"Invalid kind: {kind_str}")
                sys.exit(1)

            exports.append((name, kind_map[kind_str], index))
    else:
        # Default: export ny_main function with auto index detection
        exports = [("ny_main", ExportEntry.KIND_FUNC, "auto")]

    # Read input
    with open(input_file, 'rb') as f:
        wasm_data = f.read()

    print(f"Input: {input_file} ({len(wasm_data)} bytes)")
    print(f"Exports to add:")
    for name, kind, index in exports:
        kind_name = {
            ExportEntry.KIND_FUNC: "func",
            ExportEntry.KIND_TABLE: "table",
            ExportEntry.KIND_MEMORY: "mem",
            ExportEntry.KIND_GLOBAL: "global"
        }[kind]
        print(f"  - {name} ({kind_name} {index})")

    # 箱理論: 箱経由でexport section追加（従来351行→100行）
    modified = add_export_section_boxed(wasm_data, exports)

    # Write output
    with open(output_file, 'wb') as f:
        f.write(modified)

    print(f"✅ Output: {output_file} ({len(modified)} bytes, +{len(modified)-len(wasm_data)} bytes)")


if __name__ == "__main__":
    main()
